-- ============================================================
-- SuGanta Assistant v2 — persuasive, join-focused chatbot.
-- Replaces flow nodes in DB (idempotent). Uses JSON unicode
-- escapes for emojis (reliable across all encodings).
-- ============================================================

UPDATE flows SET
  name = 'SuGanta Assistant',
  description = 'Advanced education chatbot — hooks visitors, showcases value, and drives sign-ups for students, teachers, and institutes.',
  trigger_type = 'keyword',
  trigger_config = '{"keywords":["hi","hello","hey","menu","start","bot","suganta","help","join","register","signup","free"],"match_type":"contains"}'::jsonb,
  entry_node_id = 'start',
  fallback_policy = '{"on_unknown_reply":"reprompt","max_reprompts":2,"on_timeout_hours":24,"on_exhaust":"handoff"}'::jsonb,
  status = 'active',
  updated_at = NOW()
WHERE id = '9799fb41-aed1-4bb6-94e1-854d909a3666';

DELETE FROM flow_nodes WHERE flow_id = '9799fb41-aed1-4bb6-94e1-854d909a3666';

INSERT INTO flow_nodes (flow_id, node_key, node_type, config, position_x, position_y) VALUES
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'start', 'start', '{"next_node_key":"hook"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'hook', 'send_message', '{"text":"\uD83D\uDE80 *Welcome to SuGanta!*\n\nIndia''s fastest-growing education platform \u2014 where *students find top tutors*, *teachers grow their career*, and *institutes reach the right audience*.\n\n\u2728 Join *100% free* in under 2 minutes.","next_node_key":"value_pitch"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'value_pitch', 'send_message', '{"text":"*Why thousands choose SuGanta:*\n\n\uD83D\uDCDA Verified tutors & institutes\n\uD83C\uDFAF Real student leads for educators\n\uD83E\uDD16 Kaalo AI \u2014 24/7 study support\n\uD83D\uDED2 Marketplace for learning resources\n\uD83D\uDCF1 Online + offline \u2014 learn your way\n\n\uD83D\uDC47 Pick your path to get started:","next_node_key":"role_pick"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'role_pick', 'send_buttons', '{"text":"Tell us who you are \u2014 we''ll show you exactly how SuGanta helps *you* succeed:","footer_text":"Free to join \u00b7 No credit card","buttons":[{"reply_id":"student","title":"Join as Student","next_node_key":"student_intro"},{"reply_id":"teacher","title":"I''m a Teacher","next_node_key":"teacher_intro"},{"reply_id":"more","title":"Explore Features","next_node_key":"hub_list"}]}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'student_intro', 'send_message', '{"text":"\uD83D\uDCDA *Student Hub*\n\nImagine the *perfect tutor*, *study materials*, and an *AI assistant* \u2014 all in one app.\n\nSuGanta students get:\n\u2022 Personalised tutor matches\n\u2022 Verified institutes near you\n\u2022 Kaalo AI for instant help\n\nExplore below or *join free* now \uD83D\uDC47","next_node_key":"student_menu"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'student_menu', 'send_list', '{"text":"What interests you most?","button_label":"Student menu","footer_text":"Join free at app.suganta.com","sections":[{"title":"For Students","rows":[{"reply_id":"join","title":"Join Free Now","description":"Create account free","next_node_key":"msg_join"},{"reply_id":"tutor","title":"Find Tutor","description":"Top-rated teachers","next_node_key":"msg_tutor"},{"reply_id":"institute","title":"Institutes","description":"Verified academies","next_node_key":"msg_institute"},{"reply_id":"store","title":"Study Store","description":"Notes & guides","next_node_key":"msg_store"},{"reply_id":"market","title":"Marketplace","description":"Buy & sell resources","next_node_key":"msg_market"},{"reply_id":"kaalo","title":"Kaalo AI","description":"AI study buddy","next_node_key":"msg_kaalo"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'teacher_intro', 'send_message', '{"text":"\uD83D\uDC68\u200D\uD83C\uDFEB *Teacher Hub*\n\nTurn your expertise into *real opportunities*.\n\nEducators on SuGanta get:\n\u2022 Student leads delivered to you\n\u2022 A professional public profile\n\u2022 Online & offline teaching options\n\u2022 Reviews that build your brand\n\n*Start earning more* \u2014 create your profile today \uD83D\uDC47","next_node_key":"teacher_menu"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'teacher_menu', 'send_list', '{"text":"Ready to grow your teaching career?","button_label":"Teacher menu","sections":[{"title":"For Educators","rows":[{"reply_id":"join","title":"Join Free Now","description":"Create profile free","next_node_key":"msg_join_teacher"},{"reply_id":"benefits","title":"View Benefits","description":"Why educators join","next_node_key":"msg_benefits"},{"reply_id":"profile","title":"Create Profile","description":"Takes 2 minutes","next_node_key":"msg_profile"},{"reply_id":"website","title":"Visit Website","description":"Success stories","next_node_key":"msg_website"},{"reply_id":"support","title":"Get Support","description":"Talk to our team","next_node_key":"support_ask"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'hub_list', 'send_list', '{"text":"\uD83C\uDF10 *Everything SuGanta offers* \u2014 pick any service:","button_label":"Open menu","sections":[{"title":"Platform","rows":[{"reply_id":"join","title":"Join Free Now","description":"Sign up in 2 min","next_node_key":"msg_join"},{"reply_id":"students","title":"Students","description":"Find tutors & more","next_node_key":"student_intro"},{"reply_id":"teachers","title":"Teachers","description":"Grow your career","next_node_key":"teacher_intro"},{"reply_id":"institutes","title":"Institutes","description":"Partner with us","next_node_key":"msg_institutes"},{"reply_id":"market","title":"Marketplace","description":"Buy & sell resources","next_node_key":"msg_market"},{"reply_id":"kaalo","title":"Kaalo AI","description":"Free AI assistant","next_node_key":"msg_kaalo"},{"reply_id":"live","title":"Live Support","description":"Chat with team","next_node_key":"support_ask"}]}]}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_join', 'send_message', '{"text":"\uD83C\uDF89 *You''re one tap away!*\n\nJoin *50,000+* learners & educators on SuGanta \u2014 *100% free* to start.\n\n\u2705 Find tutors & institutes\n\u2705 Kaalo AI study support\n\u2705 Marketplace & resources\n\n\uD83D\uDC49 *Create your free account:*\nhttps://app.suganta.com\n\nTakes less than 2 minutes. See you inside! \uD83D\uDE80","next_node_key":"join_followup"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_join_teacher', 'send_message', '{"text":"\uD83C\uDF89 *Start your SuGanta journey!*\n\nJoin *thousands of educators* getting student leads, building profiles, and growing their income.\n\n\u2705 Free professional profile\n\u2705 Student & institute leads\n\u2705 Online + offline options\n\n\uD83D\uDC49 *Create your teacher profile:*\nhttps://app.suganta.com\n\nYour next student is waiting!","next_node_key":"join_followup"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'join_followup', 'send_buttons', '{"text":"Did you sign up? We''re excited to have you! \uD83C\uDF8A","footer_text":"Need help? Tap Talk to Expert","buttons":[{"reply_id":"app","title":"Download App","next_node_key":"msg_download"},{"reply_id":"menu","title":"Main Menu","next_node_key":"hook"},{"reply_id":"expert","title":"Talk to Expert","next_node_key":"agent_handoff"}]}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_download', 'send_message', '{"text":"\uD83D\uDCF1 *Get the SuGanta app* for the full experience:\n\nhttps://www.suganta.com/download-our-apps\n\nAvailable on Android & iOS. Learn, teach, and grow anywhere! \u2B50","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_tutor', 'send_message', '{"text":"\uD83C\uDF93 *Find Your Perfect Tutor*\n\nBrowse *verified, rated teachers* for every subject \u2014 online or in-person.\n\n\u2B50 Read reviews \u00b7 Compare profiles \u00b7 Book instantly\n\n\uD83D\uDC49 Start here:\nhttps://www.suganta.com/teachers\n\n*Tip:* Create a free account to save favourites & get matched faster!","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_institute', 'send_message', '{"text":"\uD83C\uDFEB *Find Top Institutes*\n\nDiscover *verified academies, coaching centres & schools* near you.\n\n\u2705 Compare ratings & courses\n\u2705 Online & offline options\n\n\uD83D\uDC49 Browse institutes:\nhttps://www.suganta.com/institutes?order_by=recent","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_institutes', 'send_message', '{"text":"\uD83C\uDFEB *Partner Your Institute*\n\nReach *thousands of students* actively searching for the right academy.\n\n\u2705 Verified listing on SuGanta\n\u2705 Lead generation tools\n\u2705 Collaboration network\n\n\uD83D\uDC49 Partner with us:\nhttps://www.suganta.com/institutes","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_store', 'send_message', '{"text":"\uD83D\uDCDA *Study Store*\n\nNotes, guides, question banks & more \u2014 curated by top educators.\n\n\uD83D\uDCA1 Save hours of prep time\n\n\uD83D\uDC49 Browse resources:\nhttps://www.suganta.com/store","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_market', 'send_message', '{"text":"\uD83D\uDED2 *SuGanta Marketplace*\n\nBuy & sell educational resources, services & opportunities.\n\n\uD83D\uDC49 Explore marketplace:\nhttps://app.suganta.com","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_kaalo', 'send_message', '{"text":"\uD83E\uDD16 *Meet Kaalo AI*\n\nYour *24/7 AI study companion* \u2014 ask anything, get instant answers.\n\n\u2728 Career guidance \u00b7 Homework help \u00b7 Exam prep\n\n\uD83D\uDC49 Try Kaalo AI free:\nhttps://ai.suganta.com\n\nNo sign-up needed to start chatting!","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_benefits', 'send_message', '{"text":"\uD83C\uDFAF *Why Educators Love SuGanta*\n\n\uD83D\uDCC8 More visibility \u2014 students find *you*\n\uD83D\uDCBC Flexible schedule \u2014 teach on *your* terms\n\u2B50 Build reputation with verified reviews\n\uD83E\uDD1D Connect with institutes & academies\n\uD83D\uDCB0 Multiple income streams\n\n\uD83D\uDC49 Join free today:\nhttps://app.suganta.com","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_profile', 'send_message', '{"text":"\uD83D\uDCDD *Create Your Teacher Profile*\n\nStand out to students & institutes in just *2 minutes*.\n\n\u2705 Showcase your expertise\n\u2705 Set your availability\n\u2705 Start receiving leads\n\n\uD83D\uDC49 Create profile now:\nhttps://app.suganta.com","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'msg_website', 'send_message', '{"text":"\uD83C\uDF10 *Explore SuGanta*\n\nTutors \u00b7 Institutes \u00b7 Courses \u00b7 AI \u00b7 Marketplace \u2014 everything education in one place.\n\n\uD83D\uDC49 Visit:\nhttps://www.suganta.com","next_node_key":"post_action"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'post_action', 'send_buttons', '{"text":"Ready to take the next step? \uD83D\uDE80","footer_text":"Free to join \u00b7 Cancel anytime","buttons":[{"reply_id":"join","title":"Join Free Now","next_node_key":"msg_join"},{"reply_id":"menu","title":"Main Menu","next_node_key":"hook"},{"reply_id":"done","title":"All Done","next_node_key":"end"}]}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'support_ask', 'collect_input', '{"prompt_text":"\uD83D\uDCAC *We''re here to help!*\n\nType your question and a SuGanta expert will reply shortly.\n\nWhether it''s about joining, finding a tutor, or setting up your profile \u2014 we''ve got you covered. \uD83D\uDE0A","var_key":"support_message","next_node_key":"support_handoff"}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'agent_handoff', 'handoff', '{"note":"High-intent lead — requested expert from SuGanta Assistant."}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'support_handoff', 'handoff', '{"note":"Support request via SuGanta Assistant — see flow vars."}'::jsonb, 0, 0),
('9799fb41-aed1-4bb6-94e1-854d909a3666', 'end', 'end', '{}'::jsonb, 0, 0);

UPDATE flow_runs SET
  status = 'failed',
  end_reason = 'flow_upgraded_v2',
  ended_at = NOW()
WHERE flow_id = '9799fb41-aed1-4bb6-94e1-854d909a3666' AND status = 'active';
