-- ============================================================
-- SuGanta Assistant v3 — advanced bot with registration fees,
-- app download funnel, lead capture, and full graph connectivity.
-- ============================================================

UPDATE flows SET
  name = 'SuGanta Assistant',
  description = 'Advanced registration & leads bot — pricing, app download, lead capture, and role-based onboarding.',
  trigger_type = 'keyword',
  trigger_config = '{"keywords":["hi","hello","hey","menu","start","bot","suganta","help","join","register","signup","free","download","app","fee","fees","price","lead"],"match_type":"contains"}'::jsonb,
  entry_node_id = 'start',
  fallback_policy = '{"on_unknown_reply":"reprompt","max_reprompts":2,"on_timeout_hours":24,"on_exhaust":"handoff"}'::jsonb,
  status = 'active',
  updated_at = NOW()
WHERE id = '9799fb41-aed1-4bb6-94e1-854d909a3666';

DELETE FROM flow_nodes WHERE flow_id = '9799fb41-aed1-4bb6-94e1-854d909a3666';

INSERT INTO flow_nodes (flow_id, node_key, node_type, config, position_x, position_y) VALUES
('9799fb41-aed1-4bb6-94e1-854d909a3666','start','start','{"next_node_key":"hook"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','hook','send_message','{"text":"\uD83D\uDE80 *Welcome to SuGanta!*\n\nIndia''s #1 smart education platform \u2014 tutors, institutes, AI study support & a powerful mobile app.\n\n\u2728 *Students join FREE.* Educators & institutes get *limited-time discounts* today.","next_node_key":"value_pitch"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','value_pitch','send_message','{"text":"*Why 50,000+ users trust SuGanta:*\n\n\uD83D\uDCDA Verified tutors & institutes\n\uD83C\uDFAF Real student leads for educators\n\uD83E\uDD16 Kaalo AI \u2014 24/7 study help\n\uD83D\uDCF1 Full-featured Android & iOS app\n\uD83D\uDCB3 Secure online registration & payment\n\n\uD83D\uDC47 Choose your role to see fees & next steps:","next_node_key":"role_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','role_menu','send_list','{"text":"Select your role \u2014 we''ll guide you through registration:","button_label":"Choose role","footer_text":"Student registration is 100% FREE","sections":[{"title":"I am a...","rows":[{"reply_id":"student","title":"Student (FREE)","description":"Rs 0 registration","next_node_key":"student_intro"},{"reply_id":"teacher","title":"Teacher (Rs299)","description":"Was Rs 1000","next_node_key":"teacher_intro"},{"reply_id":"institute","title":"Institute (Rs499)","description":"Was Rs 3000","next_node_key":"institute_intro"},{"reply_id":"university","title":"University (Rs599)","description":"Was Rs 5000","next_node_key":"university_intro"},{"reply_id":"fees","title":"All Fee Details","description":"Full pricing list","next_node_key":"msg_all_fees"},{"reply_id":"download","title":"Download App","description":"Android & iOS","next_node_key":"msg_download"},{"reply_id":"explore","title":"Explore Platform","description":"All services","next_node_key":"hub_list"},{"reply_id":"support","title":"Live Support","description":"Talk to expert","next_node_key":"support_ask"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_all_fees','send_message','{"text":"\uD83D\uDCB3 *SuGanta Registration Fees (INR)*\n\n*\uD83C\uDF93 Student* \u2014 *FREE* (Rs 0)\nNo payment required. Register & start instantly.\n\n*\uD83D\uDC68\u200D\uD83C\uDFEB Teacher* \u2014 *Rs 299* ~~Rs 1,000~~\nOne-time registration fee. Payment after email verification.\n\n*\uD83C\uDFEB Institute* \u2014 *Rs 499* ~~Rs 3,000~~\nList your academy & receive student leads.\n\n*\uD83C\uDFDB\uFE0F University* \u2014 *Rs 599* ~~Rs 5,000~~\nPartner at scale with national visibility.\n\n*\uD83D\uDCCB Registration steps:*\n1\uFE0F\u20E3 Sign up at app.suganta.com\n2\uFE0F\u20E3 Verify your email\n3\uFE0F\u20E3 Pay fee (if applicable)\n4\uFE0F\u20E3 Account activated \u2713","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','student_intro','send_message','{"text":"\uD83C\uDF93 *Student Registration \u2014 100% FREE*\n\n\u2705 *Rs 0* registration fee\n\u2705 Find tutors & institutes\n\u2705 Kaalo AI study assistant\n\u2705 Study store & marketplace\n\n*No payment needed* \u2014 verify email & you''re in!\n\n\uD83D\uDC47 Pick your next step:","next_node_key":"student_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','student_menu','send_list','{"text":"Student hub \u2014 what would you like?","button_label":"Student menu","sections":[{"title":"Students","rows":[{"reply_id":"join","title":"Register FREE","description":"Create account","next_node_key":"collect_lead_student"},{"reply_id":"app","title":"Download App","description":"Android & iOS","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee Details","description":"Rs 0 forever","next_node_key":"msg_reg_student"},{"reply_id":"tutor","title":"Find Tutor","description":"Top teachers","next_node_key":"msg_tutor"},{"reply_id":"institute","title":"Find Institute","description":"Academies near you","next_node_key":"msg_institute"},{"reply_id":"store","title":"Study Store","description":"Notes & guides","next_node_key":"msg_store"},{"reply_id":"kaalo","title":"Kaalo AI","description":"AI study buddy","next_node_key":"msg_kaalo"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','teacher_intro','send_message','{"text":"\uD83D\uDC68\u200D\uD83C\uDFEB *Teacher Registration*\n\n*\uD83D\uDCB0 Special offer: Rs 299* (actual Rs 1,000)\n\n\u2705 Professional profile & reviews\n\u2705 Student leads delivered to you\n\u2705 Online + offline teaching\n\u2705 Institute collaborations\n\n*Payment after email verification* \u2014 secure & instant activation.\n\n\uD83D\uDC47 Choose your next step:","next_node_key":"teacher_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','teacher_menu','send_list','{"text":"Teacher hub \u2014 grow your career:","button_label":"Teacher menu","sections":[{"title":"Educators","rows":[{"reply_id":"join","title":"Register Rs299","description":"Limited offer","next_node_key":"collect_lead_teacher"},{"reply_id":"app","title":"Download App","description":"Manage profile","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee & Payment","description":"How it works","next_node_key":"msg_reg_teacher"},{"reply_id":"benefits","title":"View Benefits","description":"Why join us","next_node_key":"msg_benefits"},{"reply_id":"profile","title":"Create Profile","description":"2 min setup","next_node_key":"msg_profile"},{"reply_id":"support","title":"Live Support","description":"Ask expert","next_node_key":"support_ask"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','institute_intro','send_message','{"text":"\uD83C\uDFEB *Institute Registration*\n\n*\uD83D\uDCB0 Special offer: Rs 499* (actual Rs 3,000)\n\n\u2705 Verified institute listing\n\u2705 Student lead generation\n\u2705 Collaboration network\n\u2705 Dashboard on app & web\n\n*Payment required after email verification.*\n\n\uD83D\uDC47 Choose your next step:","next_node_key":"institute_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','institute_menu','send_list','{"text":"Institute hub \u2014 partner with SuGanta:","button_label":"Institute menu","sections":[{"title":"Institutes","rows":[{"reply_id":"join","title":"Register Rs499","description":"Limited offer","next_node_key":"collect_lead_institute"},{"reply_id":"app","title":"Download App","description":"Manage listing","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee & Payment","description":"How it works","next_node_key":"msg_reg_institute"},{"reply_id":"partner","title":"Partner Info","description":"Reach students","next_node_key":"msg_institutes"},{"reply_id":"support","title":"Live Support","description":"Ask expert","next_node_key":"support_ask"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','university_intro','send_message','{"text":"\uD83C\uDFDB\uFE0F *University Registration*\n\n*\uD83D\uDCB0 Special offer: Rs 599* (actual Rs 5,000)\n\n\u2705 National platform visibility\n\u2705 Student recruitment tools\n\u2705 Institute & course listings\n\u2705 Dedicated support team\n\n*Payment required after email verification.*\n\n\uD83D\uDC47 Choose your next step:","next_node_key":"university_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','university_menu','send_list','{"text":"University hub \u2014 scale your reach:","button_label":"University menu","sections":[{"title":"Universities","rows":[{"reply_id":"join","title":"Register Rs599","description":"Limited offer","next_node_key":"collect_lead_university"},{"reply_id":"app","title":"Download App","description":"Manage campus","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee & Payment","description":"How it works","next_node_key":"msg_reg_university"},{"reply_id":"website","title":"Visit Website","description":"Learn more","next_node_key":"msg_website"},{"reply_id":"support","title":"Live Support","description":"Ask expert","next_node_key":"support_ask"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_student','send_message','{"text":"\uD83C\uDF93 *Student Registration \u2014 FREE*\n\n*Fee:* Rs 0 (always free)\n*Payment:* Not required\n\n*Steps:*\n1\uFE0F\u20E3 Register at https://app.suganta.com\n2\uFE0F\u20E3 Verify your email\n3\uFE0F\u20E3 Start exploring tutors, institutes & Kaalo AI!\n\n\uD83D\uDCF1 Download the app for the best experience.","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_teacher','send_message','{"text":"\uD83D\uDC68\u200D\uD83C\uDFEB *Teacher Registration Fee*\n\n*Actual price:* Rs 1,000\n*Your price today:* *Rs 299* \uD83D\uDD25\n*Currency:* INR\n\n*Payment flow:*\n1\uFE0F\u20E3 Register \u2192 status: *pending email verification*\n2\uFE0F\u20E3 Verify email \u2192 status: *pending payment*\n3\uFE0F\u20E3 Pay Rs 299 securely \u2192 status: *verified* \u2713\n\nAccount activates instantly after payment.","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_institute','send_message','{"text":"\uD83C\uDFEB *Institute Registration Fee*\n\n*Actual price:* Rs 3,000\n*Your price today:* *Rs 499* \uD83D\uDD25\n*Currency:* INR\n\n*Payment flow:*\n1\uFE0F\u20E3 Register \u2192 *pending email verification*\n2\uFE0F\u20E3 Verify email \u2192 *pending payment*\n3\uFE0F\u20E3 Pay Rs 499 securely \u2192 *verified* \u2713\n\nStart receiving student leads immediately.","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_university','send_message','{"text":"\uD83C\uDFDB\uFE0F *University Registration Fee*\n\n*Actual price:* Rs 5,000\n*Your price today:* *Rs 599* \uD83D\uDD25\n*Currency:* INR\n\n*Payment flow:*\n1\uFE0F\u20E3 Register \u2192 *pending email verification*\n2\uFE0F\u20E3 Verify email \u2192 *pending payment*\n3\uFE0F\u20E3 Pay Rs 599 securely \u2192 *verified* \u2713\n\nDedicated onboarding support included.","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_student','collect_input','{"prompt_text":"\uD83D\uDCDD *Quick Registration*\n\nPlease type your *full name* to begin your FREE student account.\n\nExample: Rahul Sharma","var_key":"lead_name","next_node_key":"msg_join"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_teacher','collect_input','{"prompt_text":"\uD83D\uDCDD *Teacher Registration (Rs 299)*\n\nType your *full name* to start. We''ll save this as your lead.\n\nExample: Priya Verma","var_key":"lead_name","next_node_key":"msg_join_teacher"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_institute','collect_input','{"prompt_text":"\uD83D\uDCDD *Institute Registration (Rs 499)*\n\nType your *institute name* and contact person.\n\nExample: ABC Academy - Rajesh","var_key":"lead_name","next_node_key":"msg_join_institute"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_university','collect_input','{"prompt_text":"\uD83D\uDCDD *University Registration (Rs 599)*\n\nType your *university name* and contact person.\n\nExample: XYZ University - Dr. Mehta","var_key":"lead_name","next_node_key":"msg_join_university"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nYour *FREE* student account is one step away.\n\n\u2705 Registration fee: *Rs 0*\n\u2705 No credit card needed\n\n*\uD83D\uDC49 Register now:*\nhttps://app.suganta.com\n\nThen verify your email & start learning! \uD83D\uDE80","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join_teacher','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nComplete teacher registration for *Rs 299* (was Rs 1,000).\n\n*\uD83D\uDC49 Register & pay:*\nhttps://app.suganta.com\n\nSteps: Sign up \u2192 Verify email \u2192 Pay Rs 299 \u2192 Go live! \uD83D\uDC68\u200D\uD83C\uDFEB","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join_institute','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nComplete institute registration for *Rs 499* (was Rs 3,000).\n\n*\uD83D\uDC49 Register & pay:*\nhttps://app.suganta.com\n\nSteps: Sign up \u2192 Verify email \u2192 Pay Rs 499 \u2192 Receive leads! \uD83C\uDFEB","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join_university','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nComplete university registration for *Rs 599* (was Rs 5,000).\n\n*\uD83D\uDC49 Register & pay:*\nhttps://app.suganta.com\n\nOur team will assist with onboarding. \uD83C\uDFDB\uFE0F","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','join_followup','send_buttons','{"text":"\uD83D\uDCF1 *Download the SuGanta app* for the full experience!","footer_text":"Questions? Tap Talk to Expert","buttons":[{"reply_id":"app","title":"Download App","next_node_key":"msg_download"},{"reply_id":"expert","title":"Talk to Expert","next_node_key":"agent_handoff"},{"reply_id":"done","title":"All Done","next_node_key":"end"}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_download','send_message','{"text":"\uD83D\uDCF1 *Download SuGanta App*\n\nGet tutors, institutes, Kaalo AI, registration & payments \u2014 all in one app.\n\n*\uD83E\uDD16 Android & \uD83C\uDF4E iOS:*\nhttps://www.suganta.com/download-our-apps\n\n*\uD83C\uDF10 Or register on web:*\nhttps://app.suganta.com\n\nInstall now & unlock everything! \u2B50","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','hub_list','send_list','{"text":"\uD83C\uDF10 Explore everything on SuGanta:","button_label":"Open menu","sections":[{"title":"Platform","rows":[{"reply_id":"student","title":"Students (FREE)","description":"Rs 0 fee","next_node_key":"student_intro"},{"reply_id":"teacher","title":"Teachers (Rs299)","description":"Was Rs 1000","next_node_key":"teacher_intro"},{"reply_id":"institute","title":"Institutes (Rs499)","description":"Was Rs 3000","next_node_key":"institute_intro"},{"reply_id":"university","title":"Universities (Rs599)","description":"Was Rs 5000","next_node_key":"university_intro"},{"reply_id":"download","title":"Download App","description":"Android & iOS","next_node_key":"msg_download"},{"reply_id":"fees","title":"All Fee Details","description":"Full pricing","next_node_key":"msg_all_fees"},{"reply_id":"tutor","title":"Find Tutor","description":"Browse teachers","next_node_key":"msg_tutor"},{"reply_id":"kaalo","title":"Kaalo AI","description":"Free AI help","next_node_key":"msg_kaalo"},{"reply_id":"market","title":"Marketplace","description":"Buy & sell","next_node_key":"msg_market"},{"reply_id":"support","title":"Live Support","description":"Chat with team","next_node_key":"support_ask"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_tutor','send_message','{"text":"\uD83C\uDF93 *Find Your Perfect Tutor*\n\nBrowse verified, rated teachers \u2014 online or in-person.\n\n\uD83D\uDC49 https://www.suganta.com/teachers\n\n*Free student account* unlocks saved favourites & faster matching.","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_institutes','send_message','{"text":"\uD83C\uDFEB *Partner Your Institute*\n\nReach thousands of students searching for the right academy.\n\n*Registration:* Rs 499 (was Rs 3,000)\n\n\uD83D\uDC49 https://www.suganta.com/institutes","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_institute','send_message','{"text":"\uD83C\uDFEB *Find Top Institutes*\n\nDiscover verified academies & coaching centres near you.\n\n\uD83D\uDC49 https://www.suganta.com/institutes?order_by=recent","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_store','send_message','{"text":"\uD83D\uDCDA *Study Store*\n\nNotes, guides & question banks from top educators.\n\n\uD83D\uDC49 https://www.suganta.com/store","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_market','send_message','{"text":"\uD83D\uDED2 *SuGanta Marketplace*\n\nBuy & sell educational resources & services.\n\n\uD83D\uDC49 https://app.suganta.com","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_kaalo','send_message','{"text":"\uD83E\uDD16 *Kaalo AI \u2014 Free Study Assistant*\n\n24/7 homework help, career guidance & exam prep.\n\n\uD83D\uDC49 https://ai.suganta.com","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_benefits','send_message','{"text":"\uD83C\uDFAF *Why Educators Choose SuGanta*\n\n\uD83D\uDCC8 Student leads delivered to you\n\u2B50 Verified profile & reviews\n\uD83D\uDCBC Flexible online/offline teaching\n\uD83E\uDD1D Institute partnerships\n\uD83D\uDCB0 Only Rs 299 to join (was Rs 1,000)","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_profile','send_message','{"text":"\uD83D\uDCDD *Create Your Teacher Profile*\n\nStand out in 2 minutes. Registration fee: Rs 299.\n\n\uD83D\uDC49 https://app.suganta.com","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_website','send_message','{"text":"\uD83C\uDF10 *Explore SuGanta*\n\nTutors \u00b7 Institutes \u00b7 AI \u00b7 App \u00b7 Marketplace\n\n\uD83D\uDC49 https://www.suganta.com","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','post_action','send_buttons','{"text":"What would you like to do next? \uD83D\uDE80","footer_text":"Free student reg \u00b7 Discounted educator fees","buttons":[{"reply_id":"download","title":"Download App","next_node_key":"msg_download"},{"reply_id":"menu","title":"Main Menu","next_node_key":"hook"},{"reply_id":"done","title":"All Done","next_node_key":"end"}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','support_ask','collect_input','{"prompt_text":"\uD83D\uDCAC *Live Support*\n\nDescribe your question (registration, fees, app download, or leads).\n\nOur expert will reply shortly. \uD83D\uDE0A","var_key":"support_message","next_node_key":"support_handoff"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','agent_handoff','handoff','{"note":"High-intent lead from SuGanta bot — registration/fees/app. Check flow vars for lead_name."}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','support_handoff','handoff','{"note":"Support request via SuGanta bot — see flow vars for support_message and lead_name."}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','end','end','{}'::jsonb,0,0);

UPDATE flow_runs SET status = 'failed', end_reason = 'flow_upgraded_v3', ended_at = NOW()
WHERE flow_id = '9799fb41-aed1-4bb6-94e1-854d909a3666' AND status = 'active';
