-- ============================================================
-- SuGanta Assistant v4 — AI platform hub (ai.suganta.com),
-- expanded Kaalo AI funnel, and enhanced super-advanced bot.
-- ============================================================

UPDATE flows SET
  name = 'SuGanta Assistant',
  description = 'Super-advanced bot — AI platform, registration fees, app download, lead capture, role onboarding.',
  trigger_type = 'keyword',
  trigger_config = '{"keywords":["hi","hello","hey","menu","start","bot","suganta","help","join","register","signup","free","download","app","fee","fees","price","lead","ai","kaalo","assistant","study","exam","homework"],"match_type":"contains"}'::jsonb,
  entry_node_id = 'start',
  fallback_policy = '{"on_unknown_reply":"reprompt","max_reprompts":2,"on_timeout_hours":24,"on_exhaust":"handoff"}'::jsonb,
  status = 'active',
  updated_at = NOW()
WHERE id = '9799fb41-aed1-4bb6-94e1-854d909a3666';

DELETE FROM flow_nodes WHERE flow_id = '9799fb41-aed1-4bb6-94e1-854d909a3666';

INSERT INTO flow_nodes (flow_id, node_key, node_type, config, position_x, position_y) VALUES
('9799fb41-aed1-4bb6-94e1-854d909a3666','start','start','{"next_node_key":"hook"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','hook','send_message','{"text":"\uD83D\uDE80 *Welcome to SuGanta!*\n\nIndia''s smartest education ecosystem:\n\uD83E\uDD16 *Kaalo AI* at ai.suganta.com\n\uD83D\uDCDA Tutors & institutes\n\uD83D\uDCF1 Android & iOS app\n\n\u2728 *Students join FREE* \u00b7 Educators get *limited-time discounts* today.","next_node_key":"value_pitch"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','value_pitch','send_message','{"text":"*Why 50,000+ learners choose SuGanta:*\n\n\uD83E\uDD16 *Kaalo AI Platform* \u2014 free 24/7 study assistant\n\uD83D\uDCDA Verified tutors & institutes nationwide\n\uD83C\uDFAF Real student leads for educators\n\uD83D\uDCF1 Full app + web dashboard\n\uD83D\uDCB3 Secure registration & online payment\n\n\uD83D\uDC49 *Try AI now:* https://ai.suganta.com/\n\n\uD83D\uDC47 What would you like to explore?","next_node_key":"role_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','role_menu','send_list','{"text":"Your personal SuGanta guide \u2014 pick any option:","button_label":"Open menu","footer_text":"AI is FREE at ai.suganta.com","sections":[{"title":"Get Started","rows":[{"reply_id":"ai","title":"Kaalo AI (FREE)","description":"ai.suganta.com","next_node_key":"ai_intro"},{"reply_id":"student","title":"Student (FREE)","description":"Rs 0 registration","next_node_key":"student_intro"},{"reply_id":"teacher","title":"Teacher (Rs299)","description":"Was Rs 1000","next_node_key":"teacher_intro"},{"reply_id":"institute","title":"Institute (Rs499)","description":"Was Rs 3000","next_node_key":"institute_intro"},{"reply_id":"university","title":"University (Rs599)","description":"Was Rs 5000","next_node_key":"university_intro"},{"reply_id":"fees","title":"All Fee Details","description":"Full pricing","next_node_key":"msg_all_fees"},{"reply_id":"download","title":"Download App","description":"Android & iOS","next_node_key":"msg_download"},{"reply_id":"explore","title":"Explore Platform","description":"All services","next_node_key":"hub_list"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','ai_intro','send_message','{"text":"\uD83E\uDD16 *SuGanta AI Platform \u2014 Kaalo*\n\nYour *free* AI-powered study companion built for Indian students.\n\n\u2705 Homework & doubt solving\n\u2705 Exam & board prep (CBSE, ICSE, JEE, NEET)\n\u2705 Career & course guidance\n\u2705 Available 24/7 on web & mobile\n\n*\uD83D\uDE80 Launch Kaalo AI now:*\nhttps://ai.suganta.com/\n\nNo signup needed to start chatting!","next_node_key":"ai_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','ai_menu','send_list','{"text":"Kaalo AI hub \u2014 what do you need help with?","button_label":"AI menu","footer_text":"Free at ai.suganta.com","sections":[{"title":"Kaalo AI","rows":[{"reply_id":"open","title":"Open Kaalo AI","description":"Start chatting now","next_node_key":"msg_ai_platform"},{"reply_id":"homework","title":"Homework Help","description":"Solve any doubt","next_node_key":"msg_ai_homework"},{"reply_id":"exam","title":"Exam Prep","description":"Boards & competitive","next_node_key":"msg_ai_exam"},{"reply_id":"career","title":"Career Guide","description":"Courses & colleges","next_node_key":"msg_ai_career"},{"reply_id":"features","title":"AI Features","description":"Full capabilities","next_node_key":"msg_ai_features"},{"reply_id":"register","title":"Register FREE","description":"Unlock full access","next_node_key":"collect_lead_student"},{"reply_id":"app","title":"Download App","description":"AI on mobile","next_node_key":"msg_download"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_ai_platform','send_message','{"text":"\uD83E\uDD16 *Open SuGanta AI Platform*\n\nKaalo AI is ready to help you *right now* \u2014 completely free.\n\n*\uD83D\uDC49 Click & start:*\nhttps://ai.suganta.com/\n\n*What you can ask:*\n\u2022 Explain any topic in simple words\n\u2022 Solve maths & science problems\n\u2022 Generate practice questions\n\u2022 Plan your study schedule\n\u2022 Get career advice\n\nBookmark it \u2014 your AI tutor is always online! \u2B50","next_node_key":"post_ai_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_ai_homework','send_message','{"text":"\uD83D\uDCDD *Homework Help with Kaalo AI*\n\nStuck on a problem? Kaalo explains step-by-step \u2014 not just the answer.\n\n*Works for:* Maths \u00b7 Science \u00b7 English \u00b7 Social Studies \u00b7 Coding\n\n*\uD83D\uDC49 Try it free:*\nhttps://ai.suganta.com/\n\nType your question and get instant help! \uD83D\uDE80","next_node_key":"post_ai_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_ai_exam','send_message','{"text":"\uD83D\uDCDA *Exam Prep with Kaalo AI*\n\nCrack your exams with AI-powered revision:\n\n\u2705 CBSE & ICSE board prep\n\u2705 JEE, NEET & competitive exams\n\u2705 Mock questions & explanations\n\u2705 Last-minute revision summaries\n\n*\uD83D\uDC49 Start preparing:*\nhttps://ai.suganta.com/","next_node_key":"post_ai_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_ai_career','send_message','{"text":"\uD83C\uDFAF *Career Guidance with Kaalo AI*\n\nNot sure which course or college to pick? Kaalo helps you decide.\n\n\u2705 Stream selection after 10th/12th\n\u2705 College & course comparisons\n\u2705 Scholarship & entrance info\n\u2705 Skill & internship advice\n\n*\uD83D\uDC49 Get guidance free:*\nhttps://ai.suganta.com/","next_node_key":"post_ai_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_ai_features','send_message','{"text":"\u2728 *Kaalo AI \u2014 Full Feature List*\n\n\uD83E\uDDE0 Smart doubt solving\n\uD83D\uDCD6 Chapter summaries & notes\n\uD83D\uDCCA Study planner & reminders\n\uD83D\uDD0D Research & project help\n\uD83C\uDF93 Interview & resume tips\n\uD83C\uDF10 Multi-language support\n\n*100% FREE on SuGanta AI Platform*\n\n\uD83D\uDC49 https://ai.suganta.com/","next_node_key":"post_ai_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','post_ai_action','send_buttons','{"text":"Ready to experience India''s smartest AI tutor? \uD83E\uDD16","footer_text":"Free forever at ai.suganta.com","buttons":[{"reply_id":"open","title":"Open Kaalo AI","next_node_key":"msg_ai_platform"},{"reply_id":"register","title":"Register FREE","next_node_key":"collect_lead_student"},{"reply_id":"menu","title":"Main Menu","next_node_key":"hook"}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_all_fees','send_message','{"text":"\uD83D\uDCB3 *SuGanta Registration Fees (INR)*\n\n*\uD83C\uDF93 Student* \u2014 *FREE* (Rs 0)\nNo payment required. Register & start instantly.\n\n*\uD83D\uDC68\u200D\uD83C\uDFEB Teacher* \u2014 *Rs 299* ~~Rs 1,000~~\nOne-time fee. Payment after email verification.\n\n*\uD83C\uDFEB Institute* \u2014 *Rs 499* ~~Rs 3,000~~\nList your academy & receive student leads.\n\n*\uD83C\uDFDB\uFE0F University* \u2014 *Rs 599* ~~Rs 5,000~~\nPartner at scale with national visibility.\n\n*\uD83E\uDD16 Kaalo AI* \u2014 *FREE* for everyone\nhttps://ai.suganta.com/\n\n*\uD83D\uDCCB Steps:* Sign up \u2192 Verify email \u2192 Pay (if required) \u2192 Active \u2713","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','student_intro','send_message','{"text":"\uD83C\uDF93 *Student Registration \u2014 100% FREE*\n\n\u2705 *Rs 0* registration fee\n\u2705 Kaalo AI at ai.suganta.com \u2014 FREE\n\u2705 Find tutors & institutes\n\u2705 Study store & marketplace\n\n*No payment needed* \u2014 verify email & you''re in!\n\n\uD83D\uDC47 Pick your next step:","next_node_key":"student_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','student_menu','send_list','{"text":"Student hub \u2014 what would you like?","button_label":"Student menu","sections":[{"title":"Students","rows":[{"reply_id":"join","title":"Register FREE","description":"Create account","next_node_key":"collect_lead_student"},{"reply_id":"ai","title":"Kaalo AI (FREE)","description":"ai.suganta.com","next_node_key":"ai_intro"},{"reply_id":"app","title":"Download App","description":"Android & iOS","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee Details","description":"Rs 0 forever","next_node_key":"msg_reg_student"},{"reply_id":"tutor","title":"Find Tutor","description":"Top teachers","next_node_key":"msg_tutor"},{"reply_id":"institute","title":"Find Institute","description":"Academies near you","next_node_key":"msg_institute"},{"reply_id":"store","title":"Study Store","description":"Notes & guides","next_node_key":"msg_store"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','teacher_intro','send_message','{"text":"\uD83D\uDC68\u200D\uD83C\uDFEB *Teacher Registration*\n\n*\uD83D\uDCB0 Special offer: Rs 299* (actual Rs 1,000)\n\n\u2705 Professional profile & reviews\n\u2705 Student leads delivered to you\n\u2705 Kaalo AI tools for lesson prep\n\u2705 Online + offline teaching\n\n*Payment after email verification.*\n\n\uD83D\uDC47 Choose your next step:","next_node_key":"teacher_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','teacher_menu','send_list','{"text":"Teacher hub \u2014 grow your career:","button_label":"Teacher menu","sections":[{"title":"Educators","rows":[{"reply_id":"join","title":"Register Rs299","description":"Limited offer","next_node_key":"collect_lead_teacher"},{"reply_id":"ai","title":"Kaalo AI Tools","description":"Lesson prep AI","next_node_key":"ai_intro"},{"reply_id":"app","title":"Download App","description":"Manage profile","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee & Payment","description":"How it works","next_node_key":"msg_reg_teacher"},{"reply_id":"benefits","title":"View Benefits","description":"Why join us","next_node_key":"msg_benefits"},{"reply_id":"profile","title":"Create Profile","description":"2 min setup","next_node_key":"msg_profile"},{"reply_id":"support","title":"Live Support","description":"Ask expert","next_node_key":"support_ask"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','institute_intro','send_message','{"text":"\uD83C\uDFEB *Institute Registration*\n\n*\uD83D\uDCB0 Special offer: Rs 499* (actual Rs 3,000)\n\n\u2705 Verified institute listing\n\u2705 Student lead generation\n\u2705 Kaalo AI for student support\n\u2705 Dashboard on app & web\n\n*Payment required after email verification.*\n\n\uD83D\uDC47 Choose your next step:","next_node_key":"institute_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','institute_menu','send_list','{"text":"Institute hub \u2014 partner with SuGanta:","button_label":"Institute menu","sections":[{"title":"Institutes","rows":[{"reply_id":"join","title":"Register Rs499","description":"Limited offer","next_node_key":"collect_lead_institute"},{"reply_id":"ai","title":"Kaalo AI for Students","description":"Free AI support","next_node_key":"ai_intro"},{"reply_id":"app","title":"Download App","description":"Manage listing","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee & Payment","description":"How it works","next_node_key":"msg_reg_institute"},{"reply_id":"partner","title":"Partner Info","description":"Reach students","next_node_key":"msg_institutes"},{"reply_id":"support","title":"Live Support","description":"Ask expert","next_node_key":"support_ask"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','university_intro','send_message','{"text":"\uD83C\uDFDB\uFE0F *University Registration*\n\n*\uD83D\uDCB0 Special offer: Rs 599* (actual Rs 5,000)\n\n\u2705 National platform visibility\n\u2705 Student recruitment tools\n\u2705 Kaalo AI integration\n\u2705 Dedicated support team\n\n*Payment required after email verification.*\n\n\uD83D\uDC47 Choose your next step:","next_node_key":"university_menu"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','university_menu','send_list','{"text":"University hub \u2014 scale your reach:","button_label":"University menu","sections":[{"title":"Universities","rows":[{"reply_id":"join","title":"Register Rs599","description":"Limited offer","next_node_key":"collect_lead_university"},{"reply_id":"ai","title":"Kaalo AI Platform","description":"ai.suganta.com","next_node_key":"ai_intro"},{"reply_id":"app","title":"Download App","description":"Manage campus","next_node_key":"msg_download"},{"reply_id":"fees","title":"Fee & Payment","description":"How it works","next_node_key":"msg_reg_university"},{"reply_id":"website","title":"Visit Website","description":"Learn more","next_node_key":"msg_website"},{"reply_id":"support","title":"Live Support","description":"Ask expert","next_node_key":"support_ask"},{"reply_id":"main","title":"Main Menu","description":"Start over","next_node_key":"hook"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_student','send_message','{"text":"\uD83C\uDF93 *Student Registration \u2014 FREE*\n\n*Fee:* Rs 0 (always free)\n*Payment:* Not required\n\n*Steps:*\n1\uFE0F\u20E3 Register at https://app.suganta.com\n2\uFE0F\u20E3 Verify your email\n3\uFE0F\u20E3 Use Kaalo AI at https://ai.suganta.com/\n\n\uD83D\uDCF1 Download the app for the best experience.","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_teacher','send_message','{"text":"\uD83D\uDC68\u200D\uD83C\uDFEB *Teacher Registration Fee*\n\n*Actual price:* Rs 1,000\n*Your price today:* *Rs 299* \uD83D\uDD25\n*Currency:* INR\n\n*Payment flow:*\n1\uFE0F\u20E3 Register \u2192 *pending email verification*\n2\uFE0F\u20E3 Verify email \u2192 *pending payment*\n3\uFE0F\u20E3 Pay Rs 299 \u2192 *verified* \u2713\n\nUse Kaalo AI free at https://ai.suganta.com/ for lesson prep!","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_institute','send_message','{"text":"\uD83C\uDFEB *Institute Registration Fee*\n\n*Actual price:* Rs 3,000\n*Your price today:* *Rs 499* \uD83D\uDD25\n*Currency:* INR\n\n*Payment flow:*\n1\uFE0F\u20E3 Register \u2192 *pending email verification*\n2\uFE0F\u20E3 Verify email \u2192 *pending payment*\n3\uFE0F\u20E3 Pay Rs 499 \u2192 *verified* \u2713\n\nOffer Kaalo AI free to your students: https://ai.suganta.com/","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_reg_university','send_message','{"text":"\uD83C\uDFDB\uFE0F *University Registration Fee*\n\n*Actual price:* Rs 5,000\n*Your price today:* *Rs 599* \uD83D\uDD25\n*Currency:* INR\n\n*Payment flow:*\n1\uFE0F\u20E3 Register \u2192 *pending email verification*\n2\uFE0F\u20E3 Verify email \u2192 *pending payment*\n3\uFE0F\u20E3 Pay Rs 599 \u2192 *verified* \u2713\n\nIntegrate Kaalo AI: https://ai.suganta.com/","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_student','collect_input','{"prompt_text":"\uD83D\uDCDD *Quick Registration*\n\nType your *full name* for a FREE student account.\n\nYou also get FREE Kaalo AI access at ai.suganta.com!\n\nExample: Rahul Sharma","var_key":"lead_name","next_node_key":"msg_join"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_teacher','collect_input','{"prompt_text":"\uD83D\uDCDD *Teacher Registration (Rs 299)*\n\nType your *full name* to start.\n\nExample: Priya Verma","var_key":"lead_name","next_node_key":"msg_join_teacher"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_institute','collect_input','{"prompt_text":"\uD83D\uDCDD *Institute Registration (Rs 499)*\n\nType your *institute name* and contact person.\n\nExample: ABC Academy - Rajesh","var_key":"lead_name","next_node_key":"msg_join_institute"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','collect_lead_university','collect_input','{"prompt_text":"\uD83D\uDCDD *University Registration (Rs 599)*\n\nType your *university name* and contact person.\n\nExample: XYZ University - Dr. Mehta","var_key":"lead_name","next_node_key":"msg_join_university"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nYour *FREE* student account is one step away.\n\n\u2705 Registration: *Rs 0*\n\u2705 Kaalo AI: *FREE* at ai.suganta.com\n\n*\uD83D\uDC49 Register now:*\nhttps://app.suganta.com\n\n*\uD83E\uDD16 Try AI now:*\nhttps://ai.suganta.com/","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join_teacher','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nComplete teacher registration for *Rs 299* (was Rs 1,000).\n\n*\uD83D\uDC49 Register & pay:*\nhttps://app.suganta.com\n\n*\uD83E\uDD16 Free AI tools:*\nhttps://ai.suganta.com/","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join_institute','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nComplete institute registration for *Rs 499* (was Rs 3,000).\n\n*\uD83D\uDC49 Register & pay:*\nhttps://app.suganta.com\n\n*\uD83E\uDD16 Free AI for students:*\nhttps://ai.suganta.com/","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_join_university','send_message','{"text":"\uD83C\uDF89 *Thank you, {{vars.lead_name}}!*\n\nComplete university registration for *Rs 599* (was Rs 5,000).\n\n*\uD83D\uDC49 Register & pay:*\nhttps://app.suganta.com\n\nOur team will assist with onboarding. \uD83C\uDFDB\uFE0F","next_node_key":"join_followup"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','join_followup','send_buttons','{"text":"You''re almost there! What''s next? \uD83D\uDE80","footer_text":"AI free at ai.suganta.com","buttons":[{"reply_id":"ai","title":"Open Kaalo AI","next_node_key":"msg_ai_platform"},{"reply_id":"app","title":"Download App","next_node_key":"msg_download"},{"reply_id":"expert","title":"Talk to Expert","next_node_key":"agent_handoff"}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_download','send_message','{"text":"\uD83D\uDCF1 *Download SuGanta App*\n\nEverything in one place:\n\u2022 Tutors & institutes\n\u2022 Kaalo AI study assistant\n\u2022 Registration & payments\n\u2022 Study store & marketplace\n\n*\uD83E\uDD16 Android & \uD83C\uDF4E iOS:*\nhttps://www.suganta.com/download-our-apps\n\n*\uD83E\uDD16 Kaalo AI on web:*\nhttps://ai.suganta.com/\n\n*\uD83C\uDF10 Register on web:*\nhttps://app.suganta.com","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','hub_list','send_list','{"text":"\uD83C\uDF10 Explore everything on SuGanta:","button_label":"Open menu","sections":[{"title":"Platform","rows":[{"reply_id":"ai","title":"Kaalo AI (FREE)","description":"ai.suganta.com","next_node_key":"ai_intro"},{"reply_id":"student","title":"Students (FREE)","description":"Rs 0 fee","next_node_key":"student_intro"},{"reply_id":"teacher","title":"Teachers (Rs299)","description":"Was Rs 1000","next_node_key":"teacher_intro"},{"reply_id":"institute","title":"Institutes (Rs499)","description":"Was Rs 3000","next_node_key":"institute_intro"},{"reply_id":"university","title":"Universities (Rs599)","description":"Was Rs 5000","next_node_key":"university_intro"},{"reply_id":"download","title":"Download App","description":"Android & iOS","next_node_key":"msg_download"},{"reply_id":"fees","title":"All Fee Details","description":"Full pricing","next_node_key":"msg_all_fees"},{"reply_id":"tutor","title":"Find Tutor","description":"Browse teachers","next_node_key":"msg_tutor"},{"reply_id":"market","title":"Marketplace","description":"Buy & sell","next_node_key":"msg_market"},{"reply_id":"support","title":"Live Support","description":"Chat with team","next_node_key":"support_ask"}]}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_tutor','send_message','{"text":"\uD83C\uDF93 *Find Your Perfect Tutor*\n\nBrowse verified, rated teachers \u2014 online or in-person.\n\n\uD83D\uDC49 https://www.suganta.com/teachers\n\n*Tip:* Use Kaalo AI at ai.suganta.com to prep before your first class!","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_institutes','send_message','{"text":"\uD83C\uDFEB *Partner Your Institute*\n\nReach thousands of students searching for the right academy.\n\n*Registration:* Rs 499 (was Rs 3,000)\n\n\uD83D\uDC49 https://www.suganta.com/institutes","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_institute','send_message','{"text":"\uD83C\uDFEB *Find Top Institutes*\n\nDiscover verified academies & coaching centres near you.\n\n\uD83D\uDC49 https://www.suganta.com/institutes?order_by=recent","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_store','send_message','{"text":"\uD83D\uDCDA *Study Store*\n\nNotes, guides & question banks from top educators.\n\n\uD83D\uDC49 https://www.suganta.com/store\n\n*Bonus:* Ask Kaalo AI to explain any topic from your notes!","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_market','send_message','{"text":"\uD83D\uDED2 *SuGanta Marketplace*\n\nBuy & sell educational resources & services.\n\n\uD83D\uDC49 https://app.suganta.com","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_benefits','send_message','{"text":"\uD83C\uDFAF *Why Educators Choose SuGanta*\n\n\uD83D\uDCC8 Student leads delivered to you\n\u2B50 Verified profile & reviews\n\uD83E\uDD16 Free Kaalo AI for lesson prep\n\uD83D\uDCBC Flexible online/offline teaching\n\uD83D\uDCB0 Only Rs 299 to join (was Rs 1,000)","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_profile','send_message','{"text":"\uD83D\uDCDD *Create Your Teacher Profile*\n\nStand out in 2 minutes. Registration fee: Rs 299.\n\n\uD83D\uDC49 https://app.suganta.com\n\nUse https://ai.suganta.com/ to draft your bio & teaching highlights!","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','msg_website','send_message','{"text":"\uD83C\uDF10 *Explore SuGanta*\n\nTutors \u00b7 Institutes \u00b7 AI \u00b7 App \u00b7 Marketplace\n\n\uD83D\uDC49 https://www.suganta.com\n\uD83E\uDD16 AI: https://ai.suganta.com/","next_node_key":"post_action"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','post_action','send_buttons','{"text":"What would you like to do next? \uD83D\uDE80","footer_text":"AI free at ai.suganta.com","buttons":[{"reply_id":"ai","title":"Open Kaalo AI","next_node_key":"msg_ai_platform"},{"reply_id":"menu","title":"Main Menu","next_node_key":"hook"},{"reply_id":"done","title":"All Done","next_node_key":"end"}]}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','support_ask','collect_input','{"prompt_text":"\uD83D\uDCAC *Live Support*\n\nDescribe your question \u2014 registration, fees, app download, Kaalo AI, or leads.\n\nOur expert will reply shortly. \uD83D\uDE0A","var_key":"support_message","next_node_key":"support_handoff"}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','agent_handoff','handoff','{"note":"High-intent lead from SuGanta bot — registration/fees/AI/app. Check flow vars for lead_name."}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','support_handoff','handoff','{"note":"Support request via SuGanta bot — see flow vars for support_message and lead_name."}'::jsonb,0,0),
('9799fb41-aed1-4bb6-94e1-854d909a3666','end','end','{}'::jsonb,0,0);

UPDATE flow_runs SET status = 'failed', end_reason = 'flow_upgraded_v4', ended_at = NOW()
WHERE flow_id = '9799fb41-aed1-4bb6-94e1-854d909a3666' AND status = 'active';
